# Generated by Django 4.0.10 on 2023-03-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Bathtub',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Fire_extinguisher',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Gym',
        ),
        migrations.RemoveField(
            model_name='property',
            name='TV',
        ),
        migrations.RemoveField(
            model_name='property',
            name='WIFI',
        ),
        migrations.AddField(
            model_name='property',
            name='bathtub',
            field=models.BooleanField(default=False, verbose_name='bathtub'),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_extinguisher',
            field=models.BooleanField(default=False, verbose_name='fire extinguisher'),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='gym'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='property',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='tv'),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='aircondition',
            field=models.BooleanField(default=False, verbose_name='air Condition'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='swimpool',
            field=models.BooleanField(default=False, verbose_name='pool'),
        ),
    ]
