# Generated by Django 4.0.10 on 2023-03-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_bathtub_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='Pricetag',
        ),
    ]
