# Generated by Django 4.0.10 on 2023-03-31 00:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('detailed_address', models.CharField(max_length=120)),
                ('zip_postcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(blank=True, error_messages={'invalid': 'Enter a valid email address'}, max_length=254, null=True)),
                ('property_type', models.CharField(max_length=128)),
                ('bedrooms', models.PositiveIntegerField()),
                ('washrooms', models.PositiveIntegerField()),
                ('livingrooms', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField()),
                ('place_type', models.CharField(blank=True, max_length=120, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('swimpool', models.BooleanField(default=False, verbose_name='pool')),
                ('wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('tv', models.BooleanField(default=False, verbose_name='tv')),
                ('gym', models.BooleanField(default=False, verbose_name='gym')),
                ('fire_extinguisher', models.BooleanField(default=False, verbose_name='fire extinguisher')),
                ('aircondition', models.BooleanField(default=False, verbose_name='air Condition')),
                ('parking', models.BooleanField(default=False, verbose_name='parking')),
                ('bathtub', models.BooleanField(default=False, verbose_name='bathtub')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('price', models.FloatField(default=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='property_image/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricetag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField(default=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
