# Generated by Django 4.0.10 on 2023-04-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image8',
        ),
    ]
