# Generated by Django 4.0.10 on 2023-04-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_image4_remove_property_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
    ]
