# Generated by Django 4.0.10 on 2023-03-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed'), ('expired', 'Expired'), ('pending_canceled', 'Pending_Canceled')], default='pending', max_length=20),
        ),
    ]
