# Generated by Django 4.0.10 on 2023-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW', 'Host: New Reservation'), ('HCANCEL', 'Host: Reservation Canceled'), ('APPROVED', 'User: Approved Reservation'), ('UCANCEL', 'User: Requst Canceled')], db_column='type', max_length=200),
        ),
    ]
