# Generated by Django 4.0.10 on 2023-03-31 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_host', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed'), ('expired', 'Expired'), ('pending_canceled', 'Pending_Canceled')], default='pending', max_length=20)),
                ('reserve_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserve_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
